djangoforum/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('polls/', include('polls.urls')),
    path('forum/', include('forum.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

forum/urls.py
from django.urls import path

from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('users/<int:user_id>', views.users, name='users'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('startThread/', views.start_thread, name='start_thread'),
    path('threads/', views.threads, name='threads'),
    path('threads/<int:thread_id>', views.thread, name='thread'),
    path('threads/<int:thread_id>/deletePost/<int:post_id>', views.delete_post, name='delete_post'),
    path('threads/<int:thread_id>/editPost/<int:post_id>', views.edit_post, name='edit_post'),
    # path('messages/', views.messages, name='messages'),
    # path('messages/<int:message_container_id>/', views.conversations, name='conversations'),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Thread(models.Model):
    title = models.CharField(max_length=30)
    pub_date = models.DateTimeField()
    update_date = models.DateTimeField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

class Post(models.Model):
    post = models.TextField()
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField()

# class MessageContainer(models.Model):
#     title = models.CharField(max_length=20, null=True)
#     side_1 = models.ForeignKey(User, related_name="side_1", null=True, on_delete=models.CASCADE)
#     side_2 = models.ForeignKey(User, related_name="side_2", null=True, on_delete=models.CASCADE)
#
# class Message(models.Model):
#     recipient = models.ForeignKey(User, related_name="recipient", null=True, on_delete=models.CASCADE)
#     sender = models.ForeignKey(User, related_name="sender", null=True, on_delete=models.CASCADE)
#     text = models.TextField()
#     pub_date = models.DateTimeField()
#     message_container = models.ForeignKey(MessageContainer, null=True, on_delete=models.CASCADE)

forum/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
# from .models import Thread, Post, Message, MessageContainer
from .models import Thread, Post
from django.shortcuts import redirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.core.validators import validate_email
import datetime


def index(request):
    threads = Thread.objects.all().order_by('update_date')
    context = {'threads': threads, 'threads_list': Thread.objects.all().order_by('update_date')}
    if 'login_failed' in request.session and request.session['login_failed'] is True:
        context['login_message'] = "Wrong username or password!"
        del request.session['login_failed']
    if request.user is not None:
        context['username'] = request.user.username
    else:
        context['username'] = ""
    return render(request, 'forum/index.html', context)


def users(request):
    users = User.objects.order_by('-id')
    context = {'users': users}
    return render(request, 'forum/users.html', context)


def signin(request):
    if request.method == 'POST':
        uname = request.POST['uname']
        psw = request.POST['psw']
        user = authenticate(username=uname, password=psw)
        if user is not None:
            login(request, user)
        else:
            request.session['login_failed'] = True
    return redirect('forum:index')


def signup(request):
    if request.user.is_authenticated:
        return redirect('forum:index')
    else:
        if request.method == 'POST':
            if request.POST.get("cancel_button"):
                return redirect('forum:index')
            else:
                context = {}
                requested_username = request.POST['requested_username']
                requested_password = request.POST['requested_password']
                requested_password_repeat = request.POST['requested_password_repeat']
                requested_email = request.POST['requested_email']
                try:
                    validate_email(requested_email)
                    if User.objects.filter(username=requested_username).exists():
                        context['error_message'] = "Requested username is already taken."
                        raise ValueError
                    if User.objects.filter(email=requested_email).exists():
                        context['error_message'] = "Given email is used by another user."
                        raise ValueError
                    if requested_password != requested_password_repeat:
                        context['error_message'] = "Passwords do not match."
                        raise ValueError
                    new_user = User.objects.create_user(requested_username, requested_email, requested_password)
                except ValueError as error:
                    return render(request, 'forum/signup.html', context)
                except ValidationError:
                    context['error_message'] = "Given email address is not valid."
                    return render(request, 'forum/signup.html', context)
                else:
                    requested_firstname = request.POST['requested_first_name']
                    requested_lastname = request.POST['requested_last_name']
                    new_user.first_name = requested_firstname
                    new_user.last_name = requested_lastname
                    new_user.save()
                    user = authenticate(username=requested_username, password=requested_password)
                    if user is not None:
                        login(request, user)
                    return redirect('forum:index')
        else:
            return render(request, 'forum/signup.html')


def start_thread(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            thread_title = request.POST['thread_title']
            thread_text = request.POST['thread_text']
            new_thread = Thread.objects.create(title=thread_title, pub_date=datetime.datetime.now(),
                                               update_date=datetime.datetime.now(),
                                               owner=request.user)
            new_post = Post.objects.create(post=thread_text, thread=new_thread, user=request.user,
                                           pub_date=datetime.datetime.now())
            new_thread.save()
            new_post.save()
            return redirect('forum:index')
        else:
            return render(request, 'forum/startThread.html')
    else:
        return redirect('forum:index')


def threads(request):
    return render(request, 'forum/threads.html', {'threads_list': Thread.objects.all().order_by('update_date')})


def thread(request, thread_id):
    if request.user.is_authenticated and request.method == "POST":
        comment = request.POST['post_text']
        thread_user = Thread.objects.all().get(id=thread_id)
        post = Post.objects.create(post=comment, thread=thread_user, user=request.user,
                                   pub_date=datetime.datetime.now())
        post.save()
    thread_to_return = Thread.objects.get(id=thread_id)
    posts_to_return = Post.objects.all().filter(thread=thread_to_return).order_by('pub_date')
    context = {'thread': thread_to_return, 'posts': posts_to_return}
    return render(request, 'forum/thread.html', context)


def delete_post(request, post_id, thread_id):
    post = Post.objects.all().filter(id=post_id)
    post.delete()
    return redirect('forum:thread', thread_id=thread_id)


def edit_post(request, post_id, thread_id):
    if request.method == "POST":
        post = Post.objects.all().filter(id=post_id)
        edited_text = request.POST['edit_text']
        post.update(post=edited_text)
    return redirect('forum:thread', thread_id=thread_id)

# def messages(request):
#     message_containers_1 = MessageContainer.objects.all().filter(side_1=request.user)
#     message_containers_2 = MessageContainer.objects.all().filter(side_2=request.user)
#     message_containers = message_containers_1.union(message_containers_2)
#     context = {'message_containers' : message_containers}
#     return render(request,'forum/messages.html',context)
#
# def conversations(request, message_container_id):
#     all_messages = Message.objects.all().filter(message_container=MessageContainer.objects.all().get(id=message_container_id)).order_by('pub_date')
#     context = {'all_messages' : all_messages}
#     return render(request,'forum/conversations.html', context)

forum/templates/forum/base.html
{% load static %}
{% load glpun %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        #popover-menu-signedin, #popover-menu-guest {
            margin-left: 5px;
        }

        .bg-ege {
            background-color: #00e3ef;
        }

        .container {
            padding: 5px;
        }

        .form-control {
            width: 300px;
        }

        .popover {
            max-width: 100%;
        }

        #popover-content-logout > * {
            background-color: #ff0000 !important;
        }

        .selector-for-some-widget {
            box-sizing: content-box;
        }

        /* Sticky footer styles
        -------------------------------------------------- */
        {#html body{#}
        {#    background-color: #027B93;#}
        {
        #}#}
        html {
            position: relative;
            min-height: 100%;
        }

        body {
            /* Margin bottom by footer height */
            margin-bottom: 60px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            /* Set the fixed height of the footer here */
            height: 60px;
            line-height: 60px; /* Vertically center the text there */
            background-color: #f5f5f5;
        }

        /* Custom page CSS
        -------------------------------------------------- */
        /* Not required for template or sticky footer method. */

        body > .container {
            padding: 60px 15px 0;
        }

        .footer > .container {
            padding-right: 15px;
            padding-left: 15px;
        }

        code {
            font-size: 80%;
        }
    </style>
</head>
<header>
    <nav class="navbar navbar-expand-md" style="background-color: black;">
        <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
            <ul class="navbar-nav mr-auto">
                {% block tracker %}
                {% endblock %}
            </ul>
        </div>
        <div class="mx-auto order-0">
            <a class="navbar-brand mx-auto text-white" href="/forum">Django Forum</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
            <ul class="navbar-nav ml-auto">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <button id="popover-menu-signedin" type="button" data-container="body"
                                data-toggle="popover"
                                data-placement="bottom" style="display: inline-block; background: none; border: none;">
                            <img border="0" alt="Profile" src="{% static "forum/icons/profile.png" %}" width="40"
                                 height="40">
                        </button>
                    </li>
                    <li class="nav-item">
                        <a href="/forum/search">
                            <img border="0" alt="Search" src="{% static "forum/icons/search.png" %}" width="40"
                                 height="40">
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/forum/messages">
                            <img border="0" alt="Messages" src="{% static "forum/icons/messages.png" %}" width="40"
                                 height="40">
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="/forum/settings">
                            <img border="0" alt="Settings" src="{% static "forum/icons/settings.png" %}" width="40"
                                 height="40">
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <div id="login-form" style="display: none">
                            <form action="{% url 'forum:signin' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="uname">Username</label>
                                    <input type="text" placeholder="Enter Username" name="uname" class="form-control"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label for="psw">Password</label>
                                    <input type="password" placeholder="Enter Password" name="psw" class="form-control"
                                           required>
                                </div>
                                <div class="button-box col-lg-12" style="text-align: center; margin-top: 20px;">
                                    <button class="btn btn-primary" type="submit">Login</button>
                                    <a href="/forum/signup" class="btn btn-primary"> Signup</a>
                                </div>
                            </form>
                        </div>
                        <button id="popover-menu-guest" type="button" data-container="body"
                                data-toggle="popover"
                                data-placement="bottom" style="display: inline-block; background: none; border: none;">
                            <img border="0" alt="Profile" src="{% static "forum/icons/profile.png" %}" width="40"
                                 height="40">
                        </button>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

<body class="bg-light">
{% block content %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/holder.min.js"></script>
<script src="{% static "forum/js/forumScripts.js" %}"></script>
</body>

</html>

forum/templates/forum/conversations.html
{% extends 'forum/base.html' %}
{% load static %}
{% load glpun %}
{% block title %}
    <title>Messages</title>
{% endblock %}
{% block tracker %}
    <li class="nav-item text-white"><a href="/forum">Home</a></li>
    <li style="color: white"> -></li>
    <li class="nav-item text-white"><a href="/forum/messages">Messages</a></li>
{% endblock %}
{% block content %}
    {% for message in all_messages %}
        Message by {{ message.message_container.side_1 }} {{ message.text }}
    {% endfor %}
{% endblock %}

forum/templates/forum/indexbak.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hello, world!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <style>
        .selector-for-some-widget {
            box-sizing: content-box;
        }

        /* Sticky footer styles
        -------------------------------------------------- */
        html {
            position: relative;
            min-height: 100%;
        }

        body {
            /* Margin bottom by footer height */
            margin-bottom: 60px;
        }

        .footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            /* Set the fixed height of the footer here */
            height: 60px;
            line-height: 60px; /* Vertically center the text there */
            background-color: #f5f5f5;
        }

        /* Custom page CSS
        -------------------------------------------------- */
        /* Not required for template or sticky footer method. */

        body > .container {
            padding: 60px 15px 0;
        }

        .footer > .container {
            padding-right: 15px;
            padding-left: 15px;
        }

        code {
            font-size: 80%;
        }
    </style>
</head>
<header>
</header>
<body>
{% if threads %}
    <ul>
        {% for thread in threads %}
            <li>
                <a href="{% url 'forum:thread' thread.id %}">{{ thread.title }}</a> started by {{ thread.owner }}
            </li>
        {% endfor %}
    </ul>
    <a href="{% url 'forum:threads' %}">Click here to see details for threads.</a> <br>
{% else %}
    <p>No threads are available.</p>
{% endif %}
{% if username %}
    <p>Welcome, {{ username }}</p>
    <a href="startThread/">Click here to start a thread</a>
{% else %}
    {% if login_message %}
        <p>{{ login_message }}</p>
    {% endif %}
    <form action="{% url 'forum:signin' %}" method="post">
        {% csrf_token %}
        <label for="uname"><b>Username</b></label>
        <input type="text" placeholder="Enter Username" name="uname" required>
        <label for="psw"><b>Password</b></label>
        <input type="password" placeholder="Enter Password" name="psw" required>

        <button type="submit">Login</button>
    </form>
    <a href="{% url 'forum:signup' %}">Click here to Sign Up</a>
{% endif %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

forum/templates/forum/signup.html
{% extends 'forum/base.html' %}
{% load static %}
{% load glpun %}
{% block title %}
    <title>Sign Up</title>
{% endblock %}
{% block tracker %}
    <li class="nav-item text-white"><a href="/forum">Home</a></li>
    <li class="nav-item text-white"> -> </li>
    <li class="nav-item text-white"><a href="/forum/signup">Sign Up</a></li>
{% endblock %}
{% block content %}
    {% if error_message %}
                <div class="alert alert-danger alert-dismissible">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <strong>Signup failed!</strong> {{ error_message }}
        </div>
    {% endif %}
    <div class="container mx-auto border rounded" style="width: 400px; margin-top: 20px; padding: 5px;">
        <form action="{% url 'forum:signup' %}" method="post">
            {% csrf_token %}
            <h1>Sign Up</h1>
            <p>Please fill in this form to create an account.</p>
            <hr>

            <div class="form-group">
                <label for="first_name"><b>First Name : </b></label>
                <input type="text" class="form-control" placeholder="Enter First Name" name="requested_first_name"
                       required>
            </div>
            <div class="form-group">
                <label for="last_name"><b>Last Name : </b></label>
                <input type="text" class="form-control" placeholder="Enter Last Name" name="requested_last_name"
                       required>
            </div>
            <div class="form-group">
                <label for="email"><b>Email : </b></label>
                <input type="text" class="form-control" placeholder="Enter Email" name="requested_email" required>
            </div>
            <div class="form-group">
                <label for="username"><b>Username : </b></label>
                <input type="text" class="form-control" placeholder="Enter Username" name="requested_username" required>
            </div>
            <div class="form-group">
                <label for="psw"><b>Password : </b></label>
                <input type="password" class="form-control" placeholder="Enter Password" name="requested_password"
                       required>
            </div>
            <div class="form-group">
                <label for="psw_repeat"><b>Repeat Password : </b></label>
                <input type="password" class="form-control" placeholder="Repeat Password"
                       name="requested_password_repeat" required>
            </div>
            <button type="submit" class="btn btn-primary" name="submit_button">Sign Up</button>
            <button type="button" class="btn btn-danger" name="cancel_button">Cancel</button>

        </form>
    </div>
{% endblock %}
{#<form class="form-group" action="{% url 'forum:signup' %}"  method="post">#}
{#            {% csrf_token %}#}
{#            <h1>Sign Up</h1>#}
{#            <p>Please fill in this form to create an account.</p>#}
{#            <hr>#}
{#            <table border="1">#}
{#                <tr>#}
{#                    <td><label for="first_name"><b>First Name</b></label></td>#}
{#                    <td><input type="text" placeholder="Enter First Name" name="requested_first_name" required></td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><label for="last_name"><b>Enter Last Name</b></label></td>#}
{#                    <td><input type="text" placeholder="Enter Last Name" name="requested_last_name" required></td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><label for="email"><b>Email</b></label></td>#}
{#                    <td><input type="text" placeholder="Enter Email" name="requested_email" required></td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><label for="username"><b>Username</b></label></td>#}
{#                    <td><input type="text" placeholder="Enter Username" name="requested_username" required></td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><label for="psw"><b>Password</b></label></td>#}
{#                    <td><input type="password" placeholder="Enter Password" name="requested_password" required></td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><label for="psw_repeat"><b>Repeat Password</b></label></td>#}
{#                    <td><input type="password" placeholder="Repeat Password" name="requested_password_repeat" required>#}
{#                    </td>#}
{#                </tr>#}
{##}
{#            </table>#}
{#            <div class="clearfix">#}
{#                <button type="button" class="cancelbtn" name="cancel_button">Cancel</button>#}
{#                <button type="submit" class="signupbtn" name="submit_button">Sign Up</button>#}
{#            </div>#}
{#        </form>#}
{#    </div>#}

forum/templates/forum/startThread.html
{% extends 'forum/base.html' %}
{% load static %}
{% load glpun %}
{% block title %}
    <title>Django Forum - Start Thread</title>
{% endblock %}
{% block tracker %}
    <li class="nav-item text-white"><a href="/forum">Home</a></li>
    <li style="color: white"> -></li>
    <li class="nav-item text-white"><a href="/forum/startThread">Start Thread</a></li>
{% endblock %}
{% block content %}
    <main role="main" class="m">
    <form action="{% url 'forum:start_thread' %}" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="thread_title"><b>Thread Title: (Maximum 30 Characters)</b></label></td>
            </tr>
            <tr>
                <td><input name="thread_title" placeholder="Thread Title" type="text" maxlength="30" required></td>
            </tr>
            <tr>
                <td><textarea name="thread_text" rows="4" cols="20" required wrap="hard"></textarea></td>
            </tr>
        </table>
        <input type="submit" value="Submit">
    </form>
    </main>
{% endblock %}

forum/templates/forum/thread.html
{% extends 'forum/base.html' %}
{% load static %}
{% load glpun %}
{% block title %}
    <title>{{ thread.title }}</title>
{% endblock %}
{% block tracker %}
    <li class="nav-item text-white"><a href="/forum">Home</a></li>
    <li style="color: white"> -> </li>
    <li class="nav-item text-white"><a href="{% url 'forum:thread' thread.id %}">{{ thread.title }}</a></li>
{% endblock %}
{% block content %}
    <div class="mx-3 border rounded" style="margin-top: 20px; padding: 5px; background-color: ivory">
        {% for post in posts %}
            <div class="container border border-gray rounded my-3">
                <div class="container border-bottom rounded">
                    <p>{{ post.user.username }} posted at {{ post.pub_date }} : </p> <br>
                    <p>{{ post.post }}</p><br>
                </div>
                {% if request.user.is_authenticated and post.user == request.user %}
                    <a href="{% url 'forum:delete_post' thread.id post.id %}" class="btn btn-danger mt-2">Delete
                        Post</a>
                    <button type="button" class="btn btn-primary mt-2" data-toggle="modal"
                            data-target=".bd-example-modal-lg">Edit Post
                    </button>

                    <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog"
                         aria-labelledby="myLargeModalLabel" aria-hidden="true">
                        <div class="modal-dialog modal-lg">
                            <div class="modal-content">
                                <div class="container mx-auto" style="width: 200px;">
                                    <form action="{% url 'forum:edit_post' thread.id post.id %}" method="post">
                                        <div class="form-group">
                                            {% csrf_token %}<textarea class="form-control" name="edit_text" rows="4"
                                                                      cols="20" required
                                                                      wrap="hard">{{ post.post }}</textarea>
                                            <input type="submit" value="Edit post" class="btn btn-primary mt-2">
                                        </div>
                                </div>
                                </form>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endfor %}

        {% if request.user.is_authenticated %}
            <div class="mx-auto rounded" style="width: 400px; margin-top: 20px;">
                <form action="{% url 'forum:thread' thread.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea class="form-control" name="post_text" rows="4" cols="20" required
                                  wrap="hard"></textarea>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Submit post">
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

forum/templates/forum/threads.html
{% load glpun %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Threads</title>
    <style>
td
{
    padding:0 15px 0 15px;
}
</style>
</head>
<body>
{% if threads_list %}
    <table>
        <tr>
            <th>Thread Title</th>
            <th>Created at</th>
            <th>Started By</th>
            <th>Last Updated</th>
            <th>Last Post By</th>
        </tr>
        {% for thread in threads_list %}
            <tr>
                <td><a href="{% url 'forum:thread' thread.id%}">{{ thread.title }}</a></td>
                <td>{{ thread.pub_date }}</td>
                <td>{{ thread.owner.username }}</td>
                <td>{{ thread.update_date }}</td>
                <td>{% get_last_posts_users_name thread %}</td>
            </tr>

        {% endfor %}
    </table>
{% else %}
{% endif %}
</body>
</html>

forum/templates/forum/users.html
{% if users %}
    <ol>
    {% for user in users %}
        <li>
        {{ user.username }}
        </li>
    {% endfor %}
    </ol>
{% endif %}